version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.testing
    env_file:
      - node.env
    ports:
      - "80:80"
    command: tail -F /dev/null
  db:
    image: mongo
    restart: always
    env_file:
      - mongo.env
    ports:
      - "27017:27017"
    command: ["--bind_ip_all"]
    healthcheck:
      test: ["CMD-SHELL", "mongo"]
      interval: 10s
      timeout: 5s
      retries: 5
